### ISSUE TITLE
LSP reinvented

### ISSUE THREAD

**Issue by hinell** [piersolenski/telescope-import.nvim#10]
This could have been a standalone LSP! :smirk:

**Comment by piersolenski** [comment]
Not all languages have the same support for LSP, and not everyone uses the LSP. If I'm in Typescript land, I often use a code action to import a missing module, whereas if I'm in Javascript land, that's not an option. I also found it useful to be able to import recurring patterns of multiple imports, rather have to import each one individually. It's a plugin I made for myself, and other people have started using, you're under no obligation to use it yourself.

**Comment by hinell** [comment]
I mean it's fine. Just saying that this kind of "completion" overlaps with LSP functionality. Nice plugin anyway! Cheers!
