### ISSUE TITLE
Error with fish shell

### ISSUE THREAD

**Issue by bujesse** [piersolenski/telescope-import.nvim#17]
Fish shell considers `$` inside double-quotes as a special character and thus needs to be escaped. 

It produces this error:

![image](https://github.com/piersolenski/telescope-import.nvim/assets/139379396/66c82cc0-1de5-4d91-958a-af52a2a96ac2)

There are 2 ways to fix this; either detect the current shell and apply an escaped version if fish, _or_ allow users to override the default language settings.

I tried to do the second approach, but looking at the code, I think only the first matching filetype config gets returned; and the default built-in ones come first: https://github.com/piersolenski/telescope-import.nvim/blob/0270f1438c0ac91663146a73a213bfdc536a8cb5/lua/import/utils.lua#L52
https://github.com/piersolenski/telescope-import.nvim/blob/0270f1438c0ac91663146a73a213bfdc536a8cb5/lua/import/picker.lua#L12

I have this fixed locally by just prepending a backslash directly in the plugin code, but just wanted to raise this if others encounter this issue.

**Comment by piersolenski** [comment]
Hmm good catch 🎣!

What do you think about custom languages overwriting the defaults rather than extending them as a solution?

**Comment by bujesse** [comment]
I think all you have to do is change the order of the table merge so that user configs for a given language would take priority over the plug-in configuration.

And then maybe add something to the readme explaining this in case another fish user comes along.

I could create a PR if you like.

**Comment by piersolenski** [comment]
That'd be great, cheers!

**Comment by collindutter** [comment]
Wow what good timing, I just tried out the plugin and needed Fish support! For those coming later, here is an example config for making it work with Python:

```lua
      telescope.setup {
        extensions = {
          import = {
            insert_at_top = true,
            custom_languages = {
              {
                regex = [[(?m)^(?:from[ ]+(\S+)[ ]+)?import[ ]+(\S+)[ ]*\$]], -- Note the escaped $
                filetypes = { 'python' },
                extensions = { 'py' },
              },
            },
          },
        },
      }
```

Thanks for the awesome plugin @piersolenski, and thanks for the timely PR @bujesse!
