### ISSUE TITLE
Bug: do not suggest imports statements that already exist in a file

### ISSUE THREAD

**Issue by chrisgrieser** [piersolenski/telescope-import.nvim#24]
![Pasted image 2024-01-09 at 19 50 01@2x](https://github.com/piersolenski/telescope-import.nvim/assets/73286100/ee70711d-e84b-45ca-8730-9c8de87e7caf)

**Comment by piersolenski** [comment]
Added in https://github.com/piersolenski/telescope-import.nvim/commit/bcd39a26b65b14bbdba4bf6aee38f1800b3b256c

**Comment by chrisgrieser** [comment]
Thank you
