### ISSUE TITLE
Useful plugin, but it is not working (tried with different, but doesn't work)

### ISSUE THREAD

**Issue by daUnknownCoder** [piersolenski/telescope-import.nvim#26]
![image](https://github.com/piersolenski/telescope-import.nvim/assets/84800625/856d5760-6fbe-4fa7-8fc9-1dbd6a26c01c)
⬇️ 
*presses `fi`* [`Telescope import`]
⬇️ 
![image](https://github.com/piersolenski/telescope-import.nvim/assets/84800625/acbcc8d8-0059-40de-adac-4c1431c201a0)

`config`:
```lua
    require("telescope").setup({
        ...
        extensions = {
          ...
          import = {
            insert_at_top = true,
            custom_languages = {
              {
                regex = [[^(?:import(?:[\"'\s]*([\w*{}\n, ]+)from\s*)?[\"'\s](.*?)[\"'\s].*)]],
                filetypes = {
                  "typescript",
                  "typescriptreact",
                  "javascript",
                  "react",
                  "python",
                  "lua",
                  "c",
                  "cpp",
                  "zsh",
                  "java",
                  "bash",
                },
                extensions = {
                  "js",
                  "ts",
                  "typescript",
                  "typescriptreact",
                  "javascript",
                  "react",
                  "python",
                  "c",
                  "cpp",
                  "lua",
                  "zsh",
                  "java",
                  "bash",
                },
              },
            },
          },
        },
      })
      ...
      telescope.load_extension("import")
```

other config, where `extensions` table does not have `python`
⬇️ 
![image](https://github.com/piersolenski/telescope-import.nvim/assets/84800625/e4502fe1-ac3d-4338-859e-db2dd57eece6)

```lua
    require("telescope").setup({
        ...
        extensions = {
          ...
          import = {
            insert_at_top = true,
            custom_languages = {
              {
                regex = [[^(?:import(?:[\"'\s]*([\w*{}\n, ]+)from\s*)?[\"'\s](.*?)[\"'\s].*)]],
                filetypes = {
                  "typescript",
                  "typescriptreact",
                  "javascript",
                  "react",
                  "python",
                  "lua",
                  "c",
                  "cpp",
                  "zsh",
                  "java",
                  "bash",
                },
                extensions = {
                  "js",
                  "ts",
                },
              },
            },
          },
        },
      })
      ...
      telescope.load_extension("import")
```

other config, where `extensions` table does not have `python`, `filetypes` table also does not have python
⬇️ 
![image](https://github.com/piersolenski/telescope-import.nvim/assets/84800625/b3f63ef0-3800-4c7f-ac01-59f73af01540)
⬇️ 
[*Note that typing `from <some module> ...` and `import <some module>` does not give me results*]
⬇️ 
![image](https://github.com/piersolenski/telescope-import.nvim/assets/84800625/9216f3d1-5dc6-4314-ae57-fe56ddc4dae9)

```lua
    require("telescope").setup({
        ...
        extensions = {
          ...
          import = {
            insert_at_top = true,
            custom_languages = {
              {
                regex = [[^(?:import(?:[\"'\s]*([\w*{}\n, ]+)from\s*)?[\"'\s](.*?)[\"'\s].*)]],
                filetypes = {
                  "typescript",
                  "typescriptreact",
                  "javascript",
                  "react",
                },
                extensions = {
                  "js",
                  "ts",
                },
              },
            },
          },
        },
      })
      ...
      telescope.load_extension("import")
```

[*Same for `lua` with same config*]

**Comment by piersolenski** [comment]
Hey there!

Python and many of the other languages you're trying to add are already [supported by default.](https://github.com/piersolenski/telescope-import.nvim/blob/main/lua/import/languages.lua).

When adding custom languages, it's important that you add a separate table for each language, each with its own regex, filetypes, and extensions, rather than put it all in one single table.

Currently it looks like you're trying to use a single catch all regex, for all the different potential filetypes.

Just follow the format of the built in supported languages, or [search GitHub](https://github.com/search?q=piersolenski%2Ftelescope-import.nvim+custom_languages&type=code) to see how others have used the the custom languages option.

**Comment by daUnknownCoder** [comment]
cool, adding the `custom` table proved unnecessary ig

**Comment by daUnknownCoder** [comment]
ok so this doesnt work for `python`, tested for `js`, `ts`, `lua` but it doesnt work for python idk why
my config:
```lua
      {
        "piersolenski/telescope-import.nvim",
        lazy = true,
        keys = { { "fi", "<cmd>Telescope import<CR>", desc = "Import Modules [Telescope]" } },
        cmd = "Telescope import",
      },
```
```lua
          import = {
            insert_at_top = true,
          },
      telescope.load_extension("import")

```

**Comment by piersolenski** [comment]
From your example it looks like you're not using standard Python, and you have some form of type annotations. Can you share what your import statements look like in the project you're trying to use it in? What happens when you run `<cmd>Telescope import<cr>`?

**Comment by daUnknownCoder** [comment]
i just do `nvim <some-file>.py`
this is the code in the file:
```python
from abc import ABC, abstractmethod


class Shapes(ABC):
    @abstractmethod
    def area(self):
        pass


class Circle(Shapes):
    def __init__(self, radius):
        self.radius = radius

    def area(self):
        return (22 / 7) * self.radius * self.radius


class Rectangle(Shapes):
    def __init__(self, width, length):
        self.width = width
        self.length = length

    # def area(self):
    #     return (22 / 7) * self.length * self.width


rectangleobj = Rectangle(500, 100)
print(f"Rectangle Area: {rectangleobj.area()}")

circleobj = Circle(5)
print(f"Circle Area: {circleobj.area()}")
```
> `<cmd>Telescope import<cr>` looks like this

![image](https://github.com/piersolenski/telescope-import.nvim/assets/84800625/2da03575-9c84-43b7-ad1c-257111e60178)

for a random `lua` code, it looks like this:
![image](https://github.com/piersolenski/telescope-import.nvim/assets/84800625/59f72ed2-60b1-4cb2-9563-91fb317d139a)
for a random `js` code, it looks like this:
![image](https://github.com/piersolenski/telescope-import.nvim/assets/84800625/4fb1f5b1-ed56-4b6b-994c-48b78e4c0522)

**Comment by piersolenski** [comment]
Fixed in https://github.com/piersolenski/telescope-import.nvim/pull/28
