### ISSUE TITLE
[Error]: insert_at_top: expected boolean, got nil

### ISSUE THREAD

**Issue by Drew-Daniels** [piersolenski/telescope-import.nvim#30]
This plugin is incredibly useful, thanks for creating this!

Started having an issue where it looks like the config validation step has stopped working properly after a recent change. I'm getting this error when launching `nvim`:

![image](https://github.com/user-attachments/assets/1a4e465f-3871-41a2-90c3-fab9f21514b4)

Here is my config:

`nvim/lua/plugins/init.lua`:
```lua
return require("lazy").setup({
	{
		"piersolenski/telescope-import.nvim",
		requires = "nvim-telescope/telescope.nvim",
	},
	{
		"nvim-telescope/telescope.nvim",
		branch = "0.1.x",
		dependencies = { "nvim-lua/plenary.nvim", "rafi/telescope-thesaurus.nvim" },
	},
})

```

`nvim/init.lua`
```lua
local telescope = require("telescope")

telescope.setup({
	extensions = {
		import = {
			insert_at_top = true,
		},
	},
})

telescope.load_extension("import")
```

This config was working as expected until this morning, when I upgraded `telescope-import.nvim`:

![image](https://github.com/user-attachments/assets/9f4e1d89-2861-43ea-8353-e62454b2749e)

Even when I remove my customized `telescope.setup` configuration table, I still get the same error, so it doesn't look like it is anything in my config that's causing this - at least as far as I can tell.

```sh
NVIM v0.11.0-dev-3788+gac53996eb-Homebrew
Build type: Release
LuaJIT 2.1.1723675123
Run "nvim -V1 -v" for more info
```

![image](https://github.com/user-attachments/assets/7889a811-6cc7-4b5e-831a-66f00e490319)

**Comment by piersolenski** [comment]
Hey @Drew-Daniels - I just pushed a fix - could you let me know if it resolves the issue for you?

**Comment by Drew-Daniels** [comment]
@piersolenski Awesome - looks like it works for me! Thanks 🚀
