### ISSUE TITLE
FR: how about "just" inserting 

### ISSUE THREAD

**Issue by SwimmingPolar** [piersolenski/telescope-import.nvim#32]
even though the matching import is not found. I would find it useful if I can just insert import statement at the current cursor position without moving to the top. Of course, I can always
```
m1gg
{insert import}
`1
```
but in some perspective, it's one less context switching. With some restriction like `not found` -> `press enter on normal mode` something like this?

**Comment by piersolenski** [comment]
I really like the idea of this, but it goes outside of the functionality of a telescope extension and would need to be a separate command. There's a part of me that wants to rewrite `telescope-import.nvim` as `import.nvim` and add some additional functionality, but at the moment I don't have enough to justify doing so.
