### ISSUE TITLE
Lua requires can have no `(` `)`

### ISSUE THREAD

**Issue by bew** [piersolenski/telescope-import.nvim#33]
Hello,

I write all my Lua requires without parenthesis, like `require"foo"`, thus the plugin can't find any Lua 'imports' in my dotfiles even though there are _a lot_.

What do you think should be done in this case?
Make the parenthesis optional in the regex?
Allow multiple regex per languages? (would be the most flexible / readable IMO) 🤔

**Comment by piersolenski** [comment]
I think making the parenthesis optional in the regex would be the best solution rather than rewriting it to allow multiple languages - and regex is never particularly readable 😅

Away from laptop for a bit but happy to accept a PR, should be fairly quick, especially if you ask Mr ChatGPT.

**Comment by bew** [comment]
> Away from laptop for a bit but happy to accept a PR, should be fairly quick, especially if you ask Mr ChatGPT.

Here you go ;)
_"I don't need ChatGPT to edit a regex" skill unlocked_

**Comment by piersolenski** [comment]
You've been promoted to the leader of the Skynet Resistance my friend. We are at your command 🙏
