### ISSUE TITLE
Syntax compatiblity with html-ish languages

### ISSUE THREAD

**Issue by thenbe** [piersolenski/telescope-import.nvim#9]
Hi. I'm trying to add `svelte` as a custom language. This is what I have:

```lua
import = {
  insert_at_top = false,
  custom_languages = {
    {
      regex = [[^\s+import\s+.*from\s+]],
      filetypes = { "svelte" },
      extensions = { "svelte" }, -- custom svelte filetype is defined using ripgrep config file: https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file
    },
  },
},
```

The core functionality is working great. By default however, the imports are inserted at the top line which is incorrect syntax for svelte files. This is because a typical svelte starts like this:

```svelte
<script>
  import foo from 'bar';
</script>
```

Imports need to start at the second line.

## Solutions

1. (ideal) allow to declare a custom line number in a custom_language object:

   ```lua
   custom_languages = {
     {
       regex = [[^\s+import\s+.*from\s+]],
       filetypes = { "svelte" },
       extensions = { "svelte" },
       insert_at_line = 2; -- <-- like this
     },
   ```

1. Allow `insert_at_top` to be configurable on a `custom_language` level. Currently, you would lose insert_at_top functionality for all languages (even ts, js) if you wanted to be compatible with svelte (or vue, html, etc). It's a shame because it's such a convenient feature.

   ```lua
   custom_languages = {
     {
       regex = [[^\s+import\s+.*from\s+]],
       filetypes = { "svelte" },
       extensions = { "svelte" },
       insert_at_top = false; -- <-- only for svelte
     },
   ```

**Comment by piersolenski** [comment]
Good point! I prefer the first approach if you feel like submitting a PR for it?

**Comment by piersolenski** [comment]
Move conversation to https://github.com/piersolenski/telescope-import.nvim/issues/22
